image: loganhanks/euphoria
env:
  - GOPATH=/var/cache/drone
script:
  - /var/cache/drone/src/github.com/euphoria-io/heim/test.sh
services:
  - postgres
notify:
  email:
    recipients:
      - logan.hanks@gmail.com
