image: eu.phoria/drone-runner:12
env:
  - GOPATH=/var/cache/drone
script:
  - /var/cache/drone/src/github.com/euphoria-io/heim/ci/build.sh
services:
  - postgres
notify:
  email:
    recipients:
      - logan.hanks@gmail.com
