image: loganhanks/golang
env:
  - GOPATH=/var/cache/drone
script:
  - ln -sf /var/cache/drone/src/github.com/euphoria-io/heim /var/cache/drone/src
  - go build heim/...
  - go test -v heim/...
services:
  - postgres
notify:
  email:
    recipients:
      - logan.hanks@gmail.com
