image: eu.phoria/drone-runner:33

env:
  - DB_HOST=$POSTGRES_PORT_5432_TCP_ADDR

script:
  - mv /var/cache/drone/src/github.com/euphoria-io /var/cache/drone/src/euphoria.io
  - ci/test.sh build

services:
  - library/postgres:9.1

notify:
  webhook:
    urls:
      - http://52.10.123.209:8082/dronehook
    on_success: true
    on_failure: true
